from tkinter import *
from tkinter import ttk
import customtkinter
from PIL import Image, ImageTk
import ctypes as ct

class profileframe:
    def __init__(self,profileframe,user):
        profilepic =ImageTk.PhotoImage(Image.open("profileicon.png").resize((200,200)))
        customtkinter.CTkLabel(profileframe,image=profilepic,text="").place(relx=0.24,y=200,anchor=CENTER)
        namel=customtkinter.CTkLabel(profileframe,text=user[1].upper(),text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 23,'bold'))
        namel.place(relx=0.24,y=340,anchor=CENTER)
        namel1=customtkinter.CTkLabel(profileframe,text='ID',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        namel1.place(x=405-50,y=150-50)
        namel2=customtkinter.CTkLabel(profileframe,text='Department',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        namel2.place(x=405-50,y=200-50)
        namel3=customtkinter.CTkLabel(profileframe,text='Salary',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        namel3.place(x=405-50,y=250-50)
        namel4=customtkinter.CTkLabel(profileframe,text='Phone No',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        namel4.place(x=405-50,y=300-50)
        namel5=customtkinter.CTkLabel(profileframe,text='City',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        namel5.place(x=405-50,y=300)
        namel6=customtkinter.CTkLabel(profileframe,text='Role',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        namel6.place(x=405-50,y=350)
        named1=customtkinter.CTkLabel(profileframe,text=':',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        named1.place(x=575-50,y=150-50)
        named2=customtkinter.CTkLabel(profileframe,text=':',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        named2.place(x=575-50,y=200-50)
        named3=customtkinter.CTkLabel(profileframe,text=':',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        named3.place(x=575-50,y=250-50)
        named4=customtkinter.CTkLabel(profileframe,text=':',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        named4.place(x=575-50,y=300-50)
        named5=customtkinter.CTkLabel(profileframe,text=':',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        named5.place(x=575-50,y=300)
        named6=customtkinter.CTkLabel(profileframe,text=':',text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17,'bold'))
        named6.place(x=575-50,y=350)
        named1=customtkinter.CTkLabel(profileframe,text=str(user[0]),text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17))
        named1.place(x=590-50,y=150-50)
        named2=customtkinter.CTkLabel(profileframe,text=user[7],text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17))
        named2.place(x=590-50,y=200-50)
        named3=customtkinter.CTkLabel(profileframe,text=str(user[4]),text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17))
        named3.place(x=590-50,y=250-50)
        named4=customtkinter.CTkLabel(profileframe,text=user[5],text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17))
        named4.place(x=590-50,y=300-50)
        named5=customtkinter.CTkLabel(profileframe,text=user[6],text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17))
        named5.place(x=590-50,y=300)
        named6=customtkinter.CTkLabel(profileframe,text="Admin" if user[3]=="yes" else "Worker",text_color='black',fg_color='#E5E5E5',font=('Century Gothic', 17))
        named6.place(x=590-50,y=350)
